services:
  - type: web
    name: P7_API
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api:app --host 0.0.0.0 --port 10000
    pythonVersion: 3.10.13