name: Run Pytest

# Déclenche le workflow sur push et pull request
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Récupère le code du repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Installer Python 3.11
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install fastapi==0.110.0
        pip install starlette==0.36.3
        pip install httpx
        pip install pytest

    # Lancer les tests
    - name: Run tests
      run: |
        pytest -v tests/
